# Generated by Django 5.1.3 on 2025-01-08 14:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the office.', max_length=255)),
                ('location', models.CharField(help_text='Location of the office.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='delivery_system.office')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='What the package contains.', max_length=255)),
                ('delivery_address', models.CharField(blank=True, help_text='Address for delivery (if applicable).', max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the package in kilograms.', max_digits=5)),
                ('delivery_type', models.CharField(choices=[('office', 'Office'), ('address', 'Address')], help_text='Type of delivery: to office or address.', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('lost', 'Lost')], default='submitted', help_text='Current status of the package.', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the delivery.', max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the package was registered.', null=True)),
                ('office', models.ForeignKey(blank=True, help_text='Office location for delivery/pickup (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='delivery_system.office')),
                ('receiver', models.ForeignKey(help_text='The user who receives the package.', on_delete=django.db.models.deletion.CASCADE, related_name='received_packages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user who sent the package.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
